input_lvs = [
    {
        'X': (0, 15, 1),
        'name': 'Age',
        'terms': {
            'good': ('trapmf', 0, 0, 1, 2),
            'normal': ('trimf', 2, 3, 4),
            'average': ('trimf', 3, 4, 6),
            'mediocre': ('trimf', 5, 6, 8),
            'bad': ('trapmf', 7, 10, 15, 15),
        }
    },

    {
        'X': (0, 250000, 1),
        'name': 'Mileage',
        'terms': {
            'good': ('trapmf', 0, 0, 55000, 65000),
            'normal': ('trimf', 60000, 75000, 90000),
            'average': ('trimf', 85000, 100000, 120000),
            'mediocre': ('trimf', 100000, 115000, 140000),
            'bad': ('trapmf', 120000, 150000, 250000, 250000),
        }
    },

    {
        'X': (0, 10, 1),
        'name': 'Power unit repairments',
        'terms': {
            'good': ('trapmf', 0, 0, 1, 2),
            'normal': ('trimf', 1, 2, 3),
            'average': ('trimf', 2, 3, 4),
            'mediocre': ('trimf', 3, 4, 5),
            'bad': ('trapmf', 4, 6, 10, 10),
        }
    }
]

output_lv = {
    'X': (0, 10.1, 0.1),
    'name': 'Car condition',
    'terms': {
        'terrible': ('trapmf', 0, 0, 0.5, 2),
        'very bad': ('trapmf', 1, 2, 3, 4),
        'bad': ('trimf', 3, 4, 5),
        'normal': ('trapmf', 4, 5, 6, 7),
        'good': ('trimf', 6, 7, 8),
        'very good': ('trimf', 7, 8, 9),
        'perfect': ('trapmf', 8.5, 9, 10, 10),
    }
}

rule_base = [
    (('bad', 'bad', 'bad'), 'terrible'),
    (('bad', 'bad', 'mediocre'), 'terrible'),
    (('bad', 'bad', 'average'), 'very bad'),
    (('bad', 'bad', 'normal'), 'very bad'),
    (('bad', 'bad', 'good'), 'very bad'),
    (('bad', 'mediocre', 'bad'), 'terrible'),
    (('bad', 'mediocre', 'mediocre'), 'very bad'),
    (('bad', 'mediocre', 'average'), 'very bad'),
    (('bad', 'mediocre', 'normal'), 'very bad'),
    (('bad', 'mediocre', 'good'), 'bad'),
    (('bad', 'average', 'bad'), 'very bad'),
    (('bad', 'average', 'mediocre'), 'very bad'),
    (('bad', 'average', 'average'), 'very bad'),
    (('bad', 'average', 'normal'), 'bad'),
    (('bad', 'average', 'good'), 'normal'),
    (('bad', 'normal', 'bad'), 'very bad'),
    (('bad', 'normal', 'mediocre'), 'very bad'),
    (('bad', 'normal', 'average'), 'bad'),
    (('bad', 'normal', 'normal'), 'normal'),
    (('bad', 'normal', 'good'), 'normal'),
    (('bad', 'good', 'bad'), 'very bad'),
    (('bad', 'good', 'mediocre'), 'bad'),
    (('bad', 'good', 'average'), 'normal'),
    (('bad', 'good', 'normal'), 'normal'),
    (('bad', 'good', 'good'), 'good'),
    (('mediocre', 'bad', 'bad'), 'terrible'),
    (('mediocre', 'bad', 'mediocre'), 'very bad'),
    (('mediocre', 'bad', 'average'), 'very bad'),
    (('mediocre', 'bad', 'normal'), 'very bad'),
    (('mediocre', 'bad', 'good'), 'bad'),
    (('mediocre', 'mediocre', 'bad'), 'very bad'),
    (('mediocre', 'mediocre', 'mediocre'), 'very bad'),
    (('mediocre', 'mediocre', 'average'), 'very bad'),
    (('mediocre', 'mediocre', 'normal'), 'bad'),
    (('mediocre', 'mediocre', 'good'), 'normal'),
    (('mediocre', 'average', 'bad'), 'very bad'),
    (('mediocre', 'average', 'mediocre'), 'very bad'),
    (('mediocre', 'average', 'average'), 'bad'),
    (('mediocre', 'average', 'normal'), 'normal'),
    (('mediocre', 'average', 'good'), 'normal'),
    (('mediocre', 'normal', 'bad'), 'very bad'),
    (('mediocre', 'normal', 'mediocre'), 'bad'),
    (('mediocre', 'normal', 'average'), 'normal'),
    (('mediocre', 'normal', 'normal'), 'normal'),
    (('mediocre', 'normal', 'good'), 'good'),
    (('mediocre', 'good', 'bad'), 'bad'),
    (('mediocre', 'good', 'mediocre'), 'normal'),
    (('mediocre', 'good', 'average'), 'normal'),
    (('mediocre', 'good', 'normal'), 'good'),
    (('mediocre', 'good', 'good'), 'good'),
    (('average', 'bad', 'bad'), 'very bad'),
    (('average', 'bad', 'mediocre'), 'very bad'),
    (('average', 'bad', 'average'), 'very bad'),
    (('average', 'bad', 'normal'), 'bad'),
    (('average', 'bad', 'good'), 'normal'),
    (('average', 'mediocre', 'bad'), 'very bad'),
    (('average', 'mediocre', 'mediocre'), 'very bad'),
    (('average', 'mediocre', 'average'), 'bad'),
    (('average', 'mediocre', 'normal'), 'normal'),
    (('average', 'mediocre', 'good'), 'normal'),
    (('average', 'average', 'bad'), 'very bad'),
    (('average', 'average', 'mediocre'), 'bad'),
    (('average', 'average', 'average'), 'normal'),
    (('average', 'average', 'normal'), 'normal'),
    (('average', 'average', 'good'), 'good'),
    (('average', 'normal', 'bad'), 'bad'),
    (('average', 'normal', 'mediocre'), 'normal'),
    (('average', 'normal', 'average'), 'normal'),
    (('average', 'normal', 'normal'), 'good'),
    (('average', 'normal', 'good'), 'good'),
    (('average', 'good', 'bad'), 'normal'),
    (('average', 'good', 'mediocre'), 'normal'),
    (('average', 'good', 'average'), 'good'),
    (('average', 'good', 'normal'), 'good'),
    (('average', 'good', 'good'), 'very good'),
    (('normal', 'bad', 'bad'), 'very bad'),
    (('normal', 'bad', 'mediocre'), 'very bad'),
    (('normal', 'bad', 'average'), 'bad'),
    (('normal', 'bad', 'normal'), 'normal'),
    (('normal', 'bad', 'good'), 'normal'),
    (('normal', 'mediocre', 'bad'), 'very bad'),
    (('normal', 'mediocre', 'mediocre'), 'bad'),
    (('normal', 'mediocre', 'average'), 'normal'),
    (('normal', 'mediocre', 'normal'), 'normal'),
    (('normal', 'mediocre', 'good'), 'good'),
    (('normal', 'average', 'bad'), 'bad'),
    (('normal', 'average', 'mediocre'), 'normal'),
    (('normal', 'average', 'average'), 'normal'),
    (('normal', 'average', 'normal'), 'good'),
    (('normal', 'average', 'good'), 'good'),
    (('normal', 'normal', 'bad'), 'normal'),
    (('normal', 'normal', 'mediocre'), 'normal'),
    (('normal', 'normal', 'average'), 'good'),
    (('normal', 'normal', 'normal'), 'good'),
    (('normal', 'normal', 'good'), 'very good'),
    (('normal', 'good', 'bad'), 'normal'),
    (('normal', 'good', 'mediocre'), 'good'),
    (('normal', 'good', 'average'), 'good'),
    (('normal', 'good', 'normal'), 'very good'),
    (('normal', 'good', 'good'), 'perfect'),
    (('good', 'bad', 'bad'), 'very bad'),
    (('good', 'bad', 'mediocre'), 'bad'),
    (('good', 'bad', 'average'), 'normal'),
    (('good', 'bad', 'normal'), 'normal'),
    (('good', 'bad', 'good'), 'good'),
    (('good', 'mediocre', 'bad'), 'bad'),
    (('good', 'mediocre', 'mediocre'), 'normal'),
    (('good', 'mediocre', 'average'), 'normal'),
    (('good', 'mediocre', 'normal'), 'good'),
    (('good', 'mediocre', 'good'), 'good'),
    (('good', 'average', 'bad'), 'normal'),
    (('good', 'average', 'mediocre'), 'normal'),
    (('good', 'average', 'average'), 'good'),
    (('good', 'average', 'normal'), 'good'),
    (('good', 'average', 'good'), 'very good'),
    (('good', 'normal', 'bad'), 'normal'),
    (('good', 'normal', 'mediocre'), 'good'),
    (('good', 'normal', 'average'), 'good'),
    (('good', 'normal', 'normal'), 'very good'),
    (('good', 'normal', 'good'), 'perfect'),
    (('good', 'good', 'bad'), 'good'),
    (('good', 'good', 'mediocre'), 'good'),
    (('good', 'good', 'average'), 'very good'),
    (('good', 'good', 'normal'), 'perfect'),
    (('good', 'good', 'good'), 'terrible'),
]

